name: Build and Push Docker Image 

on: 
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: registry.cn-qingdao.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.cn-qingdao.aliyuncs.com/devindata-public/kaniko:${{ date +%s }}
